### ISSUE TITLE
i cannot run it on swift 3.0

### ISSUE THREAD

**Issue by HariNarayanan777** [lxian/LXPageViewWithButtonsViewController#1]
I just convert  the project into swift 3.0 when i open it fresh it shows error on "DemosTableViewController.swift" (line no 46)

it shows "instance member 'viewcontroller' cannot be used on type 'LXPageViewWithButtonViewController' ".....

Please  tell why its happening... on swift 3.0...

**Comment by HariNarayanan777** [comment]
Finally i run it in swift 3.0 but i want to customize to add in my project Please tell how i to do..???

Thank You...

**Comment by lxian** [comment]
@HariNarayanan777 Sorry for the late reply. I also got the same problem in swift 3.0, may I know how you resolved it ? 
And may I know what problem you got when you tried to add/customize it to your project ?

**Comment by HariNarayanan777** [comment]
just i change the 45th line on DemosTableViewController.swift "let defaultVC = LXPageViewWithButtonsViewController()"
and change 88th line as "pageViewControllerView?.translatesAutoresizingMaskIntoConstraints = false"

just change as Xcode recommended what its needed..... @lxian

**Comment by lxian** [comment]
@HariNarayanan777 
I encountered the problem in XCode 8.0 and the problem looks like disappeared in 8.1. Not sure if the Xcode upgrade fixed the issue already.
There is branch swift3 with the code that works on my computer.
